// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

/*
Package wire is a generated protocol buffer package.

It is generated from these files:
	event.proto

It has these top-level messages:
	InternalTransaction
	WireBlockSignature
	Event
*/
package wire

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InternalTransaction struct {
	Amount   uint64 `protobuf:"varint,1,opt,name=Amount" json:"Amount,omitempty"`
	Receiver []byte `protobuf:"bytes,2,opt,name=Receiver,proto3" json:"Receiver,omitempty"`
}

func (m *InternalTransaction) Reset()                    { *m = InternalTransaction{} }
func (m *InternalTransaction) String() string            { return proto.CompactTextString(m) }
func (*InternalTransaction) ProtoMessage()               {}
func (*InternalTransaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *InternalTransaction) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *InternalTransaction) GetReceiver() []byte {
	if m != nil {
		return m.Receiver
	}
	return nil
}

type WireBlockSignature struct {
	Index     int64  `protobuf:"varint,1,opt,name=Index" json:"Index,omitempty"`
	Signature string `protobuf:"bytes,2,opt,name=Signature" json:"Signature,omitempty"`
}

func (m *WireBlockSignature) Reset()                    { *m = WireBlockSignature{} }
func (m *WireBlockSignature) String() string            { return proto.CompactTextString(m) }
func (*WireBlockSignature) ProtoMessage()               {}
func (*WireBlockSignature) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *WireBlockSignature) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *WireBlockSignature) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type Event struct {
	Index                uint64                 `protobuf:"varint,1,opt,name=Index" json:"Index,omitempty"`
	Creator              []byte                 `protobuf:"bytes,2,opt,name=Creator,proto3" json:"Creator,omitempty"`
	Parents              [][]byte               `protobuf:"bytes,3,rep,name=Parents,proto3" json:"Parents,omitempty"`
	LamportTime          uint64                 `protobuf:"varint,4,opt,name=LamportTime" json:"LamportTime,omitempty"`
	InternalTransactions []*InternalTransaction `protobuf:"bytes,5,rep,name=InternalTransactions" json:"InternalTransactions,omitempty"`
	ExternalTransactions [][]byte               `protobuf:"bytes,6,rep,name=ExternalTransactions,proto3" json:"ExternalTransactions,omitempty"`
	Signature            []*WireBlockSignature  `protobuf:"bytes,7,rep,name=Signature" json:"Signature,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Event) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Event) GetCreator() []byte {
	if m != nil {
		return m.Creator
	}
	return nil
}

func (m *Event) GetParents() [][]byte {
	if m != nil {
		return m.Parents
	}
	return nil
}

func (m *Event) GetLamportTime() uint64 {
	if m != nil {
		return m.LamportTime
	}
	return 0
}

func (m *Event) GetInternalTransactions() []*InternalTransaction {
	if m != nil {
		return m.InternalTransactions
	}
	return nil
}

func (m *Event) GetExternalTransactions() [][]byte {
	if m != nil {
		return m.ExternalTransactions
	}
	return nil
}

func (m *Event) GetSignature() []*WireBlockSignature {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*InternalTransaction)(nil), "wire.InternalTransaction")
	proto.RegisterType((*WireBlockSignature)(nil), "wire.WireBlockSignature")
	proto.RegisterType((*Event)(nil), "wire.Event")
}

func init() { proto.RegisterFile("event.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x25, 0xcd, 0x47, 0xed, 0xc4, 0xd3, 0x1a, 0x64, 0x15, 0x0f, 0x21, 0xa7, 0x9c, 0x72, 0xa8,
	0xe0, 0x5d, 0xa5, 0x60, 0x40, 0x41, 0xd6, 0x82, 0xe7, 0x35, 0x0e, 0xb2, 0xd8, 0xec, 0x96, 0xc9,
	0xb6, 0xf6, 0x57, 0xf9, 0x1b, 0x25, 0xdb, 0xa6, 0x46, 0xdc, 0xe3, 0x9b, 0x37, 0xef, 0xcd, 0xe3,
	0x0d, 0xa4, 0xb8, 0x45, 0x6d, 0xab, 0x35, 0x19, 0x6b, 0x58, 0xf4, 0xa5, 0x08, 0x8b, 0x1a, 0xce,
	0x6a, 0x6d, 0x91, 0xb4, 0x5c, 0x2d, 0x49, 0xea, 0x4e, 0x36, 0x56, 0x19, 0xcd, 0xce, 0x21, 0xb9,
	0x6d, 0xcd, 0x46, 0x5b, 0x1e, 0xe4, 0x41, 0x19, 0x89, 0x03, 0x62, 0x97, 0x70, 0x22, 0xb0, 0x41,
	0xb5, 0x45, 0xe2, 0x93, 0x3c, 0x28, 0x4f, 0xc5, 0x11, 0x17, 0x0f, 0xc0, 0x5e, 0x15, 0xe1, 0xdd,
	0xca, 0x34, 0x9f, 0x2f, 0xea, 0x43, 0x4b, 0xbb, 0x21, 0x64, 0x19, 0xc4, 0xb5, 0x7e, 0xc7, 0x9d,
	0x33, 0x0a, 0xc5, 0x1e, 0xb0, 0x2b, 0x98, 0x1d, 0x57, 0x9c, 0xd1, 0x4c, 0xfc, 0x0e, 0x8a, 0xef,
	0x09, 0xc4, 0x8b, 0x3e, 0xea, 0x5f, 0x75, 0x34, 0xa8, 0x39, 0x4c, 0xef, 0x09, 0xa5, 0x35, 0x43,
	0x88, 0x01, 0xf6, 0xcc, 0xb3, 0x24, 0xd4, 0xb6, 0xe3, 0x61, 0x1e, 0xf6, 0xcc, 0x01, 0xb2, 0x1c,
	0xd2, 0x47, 0xd9, 0xae, 0x0d, 0xd9, 0xa5, 0x6a, 0x91, 0x47, 0xce, 0x6f, 0x3c, 0x62, 0x4f, 0x90,
	0x79, 0xaa, 0xe8, 0x78, 0x9c, 0x87, 0x65, 0x3a, 0xbf, 0xa8, 0xfa, 0xbe, 0x2a, 0xcf, 0x86, 0xf0,
	0xca, 0xd8, 0x1c, 0xb2, 0xc5, 0xce, 0x63, 0x97, 0xb8, 0x5c, 0x5e, 0x8e, 0xdd, 0x8c, 0x6b, 0x99,
	0xba, 0xbb, 0x7c, 0x7f, 0xf7, 0x7f, 0xb3, 0xa3, 0xc2, 0xde, 0x12, 0xf7, 0xd2, 0xeb, 0x9f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x72, 0x46, 0x84, 0x6d, 0xe1, 0x01, 0x00, 0x00,
}
