// Code generated by protoc-gen-go. DO NOT EDIT.
// source: block.proto

package poset

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BlockBody struct {
	Index                int64    `protobuf:"varint,1,opt,name=Index,proto3" json:"Index,omitempty"`
	RoundReceived        int64    `protobuf:"varint,2,opt,name=RoundReceived,proto3" json:"RoundReceived,omitempty"`
	Transactions         [][]byte `protobuf:"bytes,5,rep,name=Transactions,proto3" json:"Transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockBody) Reset()         { *m = BlockBody{} }
func (m *BlockBody) String() string { return proto.CompactTextString(m) }
func (*BlockBody) ProtoMessage()    {}
func (*BlockBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{0}
}

func (m *BlockBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockBody.Unmarshal(m, b)
}
func (m *BlockBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockBody.Marshal(b, m, deterministic)
}
func (m *BlockBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockBody.Merge(m, src)
}
func (m *BlockBody) XXX_Size() int {
	return xxx_messageInfo_BlockBody.Size(m)
}
func (m *BlockBody) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockBody.DiscardUnknown(m)
}

var xxx_messageInfo_BlockBody proto.InternalMessageInfo

func (m *BlockBody) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *BlockBody) GetRoundReceived() int64 {
	if m != nil {
		return m.RoundReceived
	}
	return 0
}

func (m *BlockBody) GetTransactions() [][]byte {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type WireBlockSignature struct {
	Index                int64    `protobuf:"varint,1,opt,name=Index,proto3" json:"Index,omitempty"`
	Signature            string   `protobuf:"bytes,2,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WireBlockSignature) Reset()         { *m = WireBlockSignature{} }
func (m *WireBlockSignature) String() string { return proto.CompactTextString(m) }
func (*WireBlockSignature) ProtoMessage()    {}
func (*WireBlockSignature) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{1}
}

func (m *WireBlockSignature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WireBlockSignature.Unmarshal(m, b)
}
func (m *WireBlockSignature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WireBlockSignature.Marshal(b, m, deterministic)
}
func (m *WireBlockSignature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WireBlockSignature.Merge(m, src)
}
func (m *WireBlockSignature) XXX_Size() int {
	return xxx_messageInfo_WireBlockSignature.Size(m)
}
func (m *WireBlockSignature) XXX_DiscardUnknown() {
	xxx_messageInfo_WireBlockSignature.DiscardUnknown(m)
}

var xxx_messageInfo_WireBlockSignature proto.InternalMessageInfo

func (m *WireBlockSignature) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *WireBlockSignature) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type Block struct {
	Body                 *BlockBody        `protobuf:"bytes,1,opt,name=Body,proto3" json:"Body,omitempty"`
	Signatures           map[string]string `protobuf:"bytes,2,rep,name=signatures,proto3" json:"signatures,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Hash                 []byte            `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Hex                  string            `protobuf:"bytes,4,opt,name=hex,proto3" json:"hex,omitempty"`
	StateHash            []byte            `protobuf:"bytes,5,opt,name=StateHash,proto3" json:"StateHash,omitempty"`
	FrameHash            []byte            `protobuf:"bytes,6,opt,name=FrameHash,proto3" json:"FrameHash,omitempty"`
	CreatedTime          int64             `protobuf:"varint,7,opt,name=CreatedTime,proto3" json:"CreatedTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{2}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetBody() *BlockBody {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Block) GetSignatures() map[string]string {
	if m != nil {
		return m.Signatures
	}
	return nil
}

func (m *Block) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Block) GetHex() string {
	if m != nil {
		return m.Hex
	}
	return ""
}

func (m *Block) GetStateHash() []byte {
	if m != nil {
		return m.StateHash
	}
	return nil
}

func (m *Block) GetFrameHash() []byte {
	if m != nil {
		return m.FrameHash
	}
	return nil
}

func (m *Block) GetCreatedTime() int64 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func init() {
	proto.RegisterType((*BlockBody)(nil), "poset.BlockBody")
	proto.RegisterType((*WireBlockSignature)(nil), "poset.WireBlockSignature")
	proto.RegisterType((*Block)(nil), "poset.Block")
	proto.RegisterMapType((map[string]string)(nil), "poset.Block.SignaturesEntry")
}

func init() { proto.RegisterFile("block.proto", fileDescriptor_8e550b1f5926e92d) }

var fileDescriptor_8e550b1f5926e92d = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x31, 0x6f, 0xfa, 0x30,
	0x10, 0xc5, 0x95, 0x84, 0xf0, 0x57, 0x2e, 0xfc, 0x55, 0x64, 0x75, 0xb0, 0x2a, 0x86, 0x28, 0x62,
	0xc8, 0x94, 0x81, 0x2e, 0x55, 0xd5, 0x2e, 0x54, 0xad, 0xe8, 0xea, 0x22, 0x75, 0x36, 0xe4, 0x54,
	0x22, 0xc0, 0x46, 0xb6, 0x41, 0xf0, 0xa5, 0xfa, 0x19, 0x2b, 0x5f, 0x44, 0x08, 0x95, 0xba, 0x9d,
	0x7f, 0xef, 0xd9, 0xf7, 0xee, 0x0c, 0xe9, 0x62, 0xa3, 0x97, 0xeb, 0x72, 0x67, 0xb4, 0xd3, 0x2c,
	0xde, 0x69, 0x8b, 0x2e, 0x5f, 0x43, 0x32, 0xf5, 0x74, 0xaa, 0xab, 0x13, 0xbb, 0x85, 0xf8, 0x5d,
	0x55, 0x78, 0xe4, 0x41, 0x16, 0x14, 0x91, 0x68, 0x0e, 0x6c, 0x0c, 0xff, 0x85, 0xde, 0xab, 0x4a,
	0xe0, 0x12, 0xeb, 0x03, 0x56, 0x3c, 0x24, 0xf5, 0x1a, 0xb2, 0x1c, 0x06, 0x73, 0x23, 0x95, 0x95,
	0x4b, 0x57, 0x6b, 0x65, 0x79, 0x9c, 0x45, 0xc5, 0x40, 0x5c, 0xb1, 0x7c, 0x06, 0xec, 0xb3, 0x36,
	0x48, 0x0d, 0x3f, 0xea, 0x2f, 0x25, 0xdd, 0xde, 0xe0, 0x1f, 0x5d, 0x47, 0x90, 0xb4, 0x16, 0xea,
	0x98, 0x88, 0x0b, 0xc8, 0xbf, 0x43, 0x88, 0xe9, 0x19, 0x36, 0x86, 0x9e, 0xcf, 0x4e, 0x97, 0xd3,
	0xc9, 0xb0, 0xa4, 0xb1, 0xca, 0x76, 0x26, 0x41, 0x2a, 0x7b, 0x02, 0xb0, 0xe7, 0xcb, 0x96, 0x87,
	0x59, 0x54, 0xa4, 0x93, 0x51, 0xd7, 0x5b, 0xb6, 0x6f, 0xdb, 0x57, 0xe5, 0xcc, 0x49, 0x74, 0xfc,
	0x8c, 0x41, 0x6f, 0x25, 0xed, 0x8a, 0x47, 0x59, 0x50, 0x0c, 0x04, 0xd5, 0x6c, 0x08, 0xd1, 0x0a,
	0x8f, 0xbc, 0x47, 0xc9, 0x7c, 0x49, 0x89, 0x9d, 0x74, 0x38, 0xf3, 0xd6, 0x98, 0xac, 0x17, 0xe0,
	0xd5, 0x37, 0x23, 0xb7, 0x8d, 0xda, 0x6f, 0xd4, 0x16, 0xb0, 0x0c, 0xd2, 0x17, 0x83, 0xd2, 0x61,
	0x35, 0xaf, 0xb7, 0xc8, 0xff, 0xd1, 0x26, 0xba, 0xe8, 0xee, 0x19, 0x6e, 0x7e, 0x45, 0xf4, 0x11,
	0xd6, 0xd8, 0x4c, 0x9e, 0x08, 0x5f, 0xfa, 0x55, 0x1e, 0xe4, 0x66, 0x7f, 0x5e, 0x58, 0x73, 0x78,
	0x0c, 0x1f, 0x82, 0x45, 0x9f, 0x7e, 0xfd, 0xfe, 0x27, 0x00, 0x00, 0xff, 0xff, 0x4d, 0xd8, 0xd9,
	0x18, 0x04, 0x02, 0x00, 0x00,
}
